### ISSUE TITLE
Agent cannot find php5.6-fpm and php7.2-fpm services

### ISSUE THREAD

**Issue by n3storm** [hetrixtools/agent#10] opened 2018-07-13 17:09 UTC
The point is php5.6-fpm and php7.2-fpm daemons both name php-fpm their processes (this why I had to specify php-fpm or agent will tell both services are down), so we will not know if one of the two daemons is down until both are down.

My suggestion is to use systemd service status (yeah, I know) in case is available, otherwise fallback to `ps -ef`

**Comment by hetrixtools** [comment] 2018-07-14 17:36
Thank you for bringing this up to our attention. Your idea of using systemd (if available) is good.

Can you please see if these changes are solving your issues: #11

We have tested it on several environments and it appears to address the issues that you have described.

**Comment by n3storm** [comment] 2018-07-15 10:28
In other to check changes I replaced function servicestatus() with new one. And it works :)

Just to let you know: Previously I replaced completely hetrixtools_agent.sh with the new version, and setup up CheckServices="" and SID="SIDPLACEHOLDER" with our server values, and script didn't work. Log was complaining at some awk parsing, no sure where.

**Comment by hetrixtools** [comment] 2018-07-15 11:17
> Just to let you know: Previously I replaced completely hetrixtools_agent.sh with the new version, and setup up CheckServices="" and SID="SIDPLACEHOLDER" with our server values, and script didn't work. Log was complaining at some awk parsing, not sure where.

Couldn't reproduce this issue using the latest agent file.

We've pushed this patch onto the main branch now, so you can now follow the regular agent installation flow and see if you still encounter any issues with awk parsing. If you do, please specify on which OS you're encountering the issues.

**Comment by n3storm** [comment] 2018-07-15 11:47
Ok. Thank you very much.

Just to be sure, if I reinstall agent now from hetrixtools dashboard I will get this new version? or should I wait longer?

**Comment by hetrixtools** [comment] 2018-07-15 12:10
> Just to be sure, if I reinstall agent now from hetrixtools dashboard I will get this new version? or should I wait longer?

You will get the new version, yes.

**Comment by n3storm** [comment] 2018-07-16 06:13
Checked and is working OK.
Thank you very much :)

**Comment by hetrixtools** [comment] 2018-07-16 06:30
You're very welcome. And thank you for raising this issue and for your feedback.
Going to close this issue now.
Have a great day.

**Closed by hetrixtools** 2018-07-16 06:30 UTC
Labels: waiting feedback
